name: Fetch Gold Rate and Update HTML

on:
  schedule:
    - cron: '34 8 * * *'  # Runs daily at 8:34 AM UTC
  workflow_dispatch:  # Allows manual run

jobs:
  fetch-gold-rate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # or any other LTS version of Node.js

    - name: Install Dependencies
      run: npm install puppeteer

    - name: Fetch Gold Rate with Puppeteer and Update HTML
      run: |
        node -e "
          const puppeteer = require('puppeteer');
          const fs = require('fs');

          async function getGoldRate() {
            try {
              console.log('Launching headless browser...');
              const browser = await puppeteer.launch();
              const page = await browser.newPage();

              console.log('Navigating to gold rate page...');
              await page.goto('https://www.malabargoldanddiamonds.com/goldprice', { waitUntil: 'networkidle2' });

              // Wait for the element containing the rate to load
              await page.waitForSelector('.price.22kt-price');

              console.log('Extracting gold rate and date...');
              const rate = await page.$eval('.price.22kt-price', el => el.textContent.trim());
              const date = await page.$eval('.date.update-date', el => el.textContent.trim());

              console.log('Gold rate:', rate);
              console.log('Date:', date);

              const newRow = \`<tr><td>\${date}</td><td>\${rate}</td></tr>\`;

              const filePath = 'index.html';
              let content = fs.readFileSync(filePath, 'utf8');
              console.log('Read existing index.html content.');

              const tableEndIndex = content.lastIndexOf('</tbody>');
              content = content.slice(0, tableEndIndex) + newRow + content.slice(tableEndIndex);

              fs.writeFileSync(filePath, content);
              console.log('Updated index.html with new gold rate.');

              await browser.close();
            } catch (error) {
              console.error('Error occurred while fetching the gold rate:', error);
            }
          }

          getGoldRate();
        "

    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Update gold rate in index.html"
        git push origin main
